# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - deps-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - deps-
      - run:
          name: install deps
          command: sudo apt-get install rsync
      - run:
          name: install python deps
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: deps-{{ checksum "requirements.txt" }}
      - run:
          name: generate site
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make html
      - add_ssh_keys:
          fingerprints:
            - "b8:b1:5d:88:21:5a:58:78:2c:e7:45:b5:7f:40:ed:c4"
      - deploy:
          name: publish site
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              python3 -m venv venv
              . venv/bin/activate
              make rsync_upload
            fi
